name: Lighthouse CI

on:
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Serve dist
        run: npx serve -s dist -l 8080 &

      - name: Run Lighthouse
        run: npx -y @lhci/cli autorun --collect.url=http://localhost:8080/ --upload.target=temporary-public-storage


